# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

# Include scripts from https://invent.kde.org/sysadmin/ci-utilities
# which run on Docker images from https://invent.kde.org/sysadmin/ci-images
include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/linux-qt6.yml
      - /gitlab-templates/freebsd-qt6.yml

